[package]
name = "float_range"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
proptest = "1.0.0"


[features]
default = []
funny_looking_forloops = []

[dependencies]
simple_bitfield = "0.1.8"
